Telegram:
  token: 12345678:abcdefghijklmnopqrstuvwxyz
MySQL:
  db_host: 127.0.0.1
  db_port: 3306
  db_database: xboard
  db_username: root
  db_password: password
Redis:
  enabled: false
  redis_host: 127.0.0.1
  redis_password: null
  redis_port: 6379
  redis_db: 2